language: cpp

addons:
  apt:
    packages:
      - gfortran
      - openmpi-bin
      - openmpi-common
      - libopenmpi-dev
      - libboost-all-dev
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libscalapack-openmpi-dev

install: true

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
