language: cpp
dist: xenial

addons:
  apt:
    packages:
      - gfortran
      - mpich
      - libmpich-dev
      - libboost-all-dev
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libscalapack-mpi-dev

install: true

script:
  - mkdir build
  - cd build
  - mkdir -p rokko rokko/build rokko/source
  - PREFIX_ROKKO=$(pwd)/rokko BUILD_DIR=$(pwd)/rokko/build SOURCE_DIR=$(pwd)/rokko/source sh ../3rd-party/install/00_env/default.sh
  - PREFIX_ROKKO=$(pwd)/rokko BUILD_DIR=$(pwd)/rokko/build SOURCE_DIR=$(pwd)/rokko/source sh ../3rd-party/install/EigenExa/default.sh
  - PREFIX_ROKKO=$(pwd)/rokko BUILD_DIR=$(pwd)/rokko/build SOURCE_DIR=$(pwd)/rokko/source sh ../3rd-party/install/EigenExa/link.sh
  - PREFIX_ROKKO=$(pwd)/rokko BUILD_DIR=$(pwd)/rokko/build SOURCE_DIR=$(pwd)/rokko/source sh ../3rd-party/install/ELPA/default.sh
  - PREFIX_ROKKO=$(pwd)/rokko BUILD_DIR=$(pwd)/rokko/build SOURCE_DIR=$(pwd)/rokko/source sh ../3rd-party/install/ELPA/link.sh
  - PREFIX_ROKKO=$(pwd)/rokko BUILD_DIR=$(pwd)/rokko/build SOURCE_DIR=$(pwd)/rokko/source sh ../3rd-party/install/Elemental/default.sh
  - PREFIX_ROKKO=$(pwd)/rokko BUILD_DIR=$(pwd)/rokko/build SOURCE_DIR=$(pwd)/rokko/source sh ../3rd-party/install/Elemental/link.sh
  - source rokko/rokkoenv.sh
  - cmake ..
  - make
  - ctest
